
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";

export const GET_BY_NAME = "GET_BY_NAME"

export const GET_BY_CONTINENT = "GET_BY_CONTINENT"

export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES"

export const COUTRIES_ORDER = "COUTRIES_ORDER"

export const POPULATION_ORDER = "POPULATION_ORDER"

export const GET_BY_ID = "GET_BY_ID"

export const GET_BY_ACTIVITY ="GET_BY_ACTIVITY"